"""M4 재무회계 테이블 생성

Revision ID: 55c454f5ad0d
Revises: f35032d40e5a
Create Date: 2026-03-15 09:16:16.437122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c454f5ad0d'
down_revision: Union[str, None] = 'f35032d40e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_of_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='계정 코드'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='계정명'),
    sa.Column('account_type', sa.String(length=30), nullable=False, comment='유형 (asset/liability/equity/revenue/expense)'),
    sa.Column('account_group', sa.String(length=50), nullable=True, comment='계정 그룹 (유동자산, 비유동자산 등)'),
    sa.Column('normal_balance', sa.String(length=10), nullable=False, comment='정상잔액 (debit/credit)'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='상위 계정'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['chart_of_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_coa_code', 'chart_of_accounts', ['code'], unique=False)
    op.create_index('idx_coa_type', 'chart_of_accounts', ['account_type'], unique=False)
    op.create_table('bank_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False, comment='이체일'),
    sa.Column('bank_name', sa.String(length=50), nullable=True, comment='은행명'),
    sa.Column('account_no', sa.String(length=50), nullable=True, comment='계좌번호'),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='총 이체 금액'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (pending/approved/completed/failed)'),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transfer_file', sa.Text(), nullable=True, comment='이체 파일 경로'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscal_years',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False, comment='회계연도'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='시작일'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='종료일'),
    sa.Column('is_closed', sa.Boolean(), nullable=False, comment='마감 여부'),
    sa.Column('closed_by', sa.UUID(), nullable=True, comment='마감 처리자'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='마감 일시'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('bank_transfer_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('payee_name', sa.String(length=100), nullable=False, comment='수취인명'),
    sa.Column('bank_name', sa.String(length=50), nullable=True, comment='은행명'),
    sa.Column('account_no', sa.String(length=50), nullable=True, comment='계좌번호'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='이체 금액'),
    sa.Column('memo', sa.String(length=100), nullable=True, comment='적요'),
    sa.Column('source_type', sa.String(length=20), nullable=True, comment='원본 유형 (payroll/expense 등)'),
    sa.Column('source_id', sa.UUID(), nullable=True, comment='원본 ID'),
    sa.ForeignKeyConstraint(['transfer_id'], ['bank_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_no', sa.String(length=30), nullable=False, comment='전표번호 (JE-YYYYMM-NNNN)'),
    sa.Column('entry_date', sa.Date(), nullable=False, comment='전표일자'),
    sa.Column('entry_type', sa.String(length=30), nullable=False, comment='전표유형 (sales/purchase/expense/payroll/general/adjustment)'),
    sa.Column('description', sa.Text(), nullable=True, comment='적요'),
    sa.Column('total_debit', sa.Numeric(precision=15, scale=2), nullable=False, comment='차변 합계'),
    sa.Column('total_credit', sa.Numeric(precision=15, scale=2), nullable=False, comment='대변 합계'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (draft/review/approved/posted/closed)'),
    sa.Column('source_module', sa.String(length=10), nullable=True, comment='원본 모듈 (M2/M3/M4/M5)'),
    sa.Column('source_id', sa.UUID(), nullable=True, comment='원본 전표 참조 ID'),
    sa.Column('fiscal_year_id', sa.UUID(), nullable=True, comment='회계연도'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='승인자'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='승인 일시'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='작성자'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_no')
    )
    op.create_index('idx_je_date', 'journal_entries', ['entry_date'], unique=False)
    op.create_index('idx_je_status', 'journal_entries', ['status'], unique=False)
    op.create_index('idx_je_type', 'journal_entries', ['entry_type'], unique=False)
    op.create_table('journal_entry_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False, comment='전표 헤더 ID'),
    sa.Column('line_no', sa.Integer(), nullable=False, comment='라인 번호'),
    sa.Column('account_id', sa.UUID(), nullable=False, comment='계정과목 ID'),
    sa.Column('debit_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='차변 금액'),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='대변 금액'),
    sa.Column('customer_id', sa.UUID(), nullable=True, comment='거래처 (선택)'),
    sa.Column('description', sa.Text(), nullable=True, comment='적요'),
    sa.Column('tax_code', sa.String(length=10), nullable=True, comment='세금 코드'),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='세액'),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=True, comment='발행번호 (TI-/TR-YYYYMM-NNNN)'),
    sa.Column('invoice_type', sa.String(length=20), nullable=False, comment='유형 (issue=매출/receive=매입)'),
    sa.Column('issue_date', sa.Date(), nullable=False, comment='발행일'),
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='거래처 ID'),
    sa.Column('supply_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='공급가액'),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='부가세액'),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='합계 금액'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (draft/sent/confirmed/cancelled)'),
    sa.Column('nts_sent_at', sa.DateTime(timezone=True), nullable=True, comment='국세청 전송 일시'),
    sa.Column('nts_result', sa.String(length=20), nullable=True, comment='국세청 전송 결과'),
    sa.Column('journal_id', sa.UUID(), nullable=True, comment='연결된 전표 ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='비고'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='작성자'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_index('idx_ti_date', 'tax_invoices', ['issue_date'], unique=False)
    op.create_index('idx_ti_status', 'tax_invoices', ['status'], unique=False)
    op.create_index('idx_ti_type', 'tax_invoices', ['invoice_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ti_type', table_name='tax_invoices')
    op.drop_index('idx_ti_status', table_name='tax_invoices')
    op.drop_index('idx_ti_date', table_name='tax_invoices')
    op.drop_table('tax_invoices')
    op.drop_table('journal_entry_lines')
    op.drop_index('idx_je_type', table_name='journal_entries')
    op.drop_index('idx_je_status', table_name='journal_entries')
    op.drop_index('idx_je_date', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_table('bank_transfer_lines')
    op.drop_table('fiscal_years')
    op.drop_table('bank_transfers')
    op.drop_index('idx_coa_type', table_name='chart_of_accounts')
    op.drop_index('idx_coa_code', table_name='chart_of_accounts')
    op.drop_table('chart_of_accounts')
    # ### end Alembic commands ###
