"""m2_영업수주_테이블_생성

Revision ID: 84eb4ff8723b
Revises: a785c9044b3b
Create Date: 2026-03-15 10:37:14.368113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84eb4ff8723b'
down_revision: Union[str, None] = 'a785c9044b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_no', sa.String(length=30), nullable=False, comment='견적번호 (QT-YYYYMM-NNNN)'),
    sa.Column('quote_date', sa.Date(), nullable=False, comment='견적일'),
    sa.Column('valid_until', sa.Date(), nullable=True, comment='유효기한'),
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='거래처'),
    sa.Column('sales_rep_id', sa.UUID(), nullable=True, comment='담당 영업사원'),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='공급가액 합계'),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='부가세 합계'),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False, comment='총액 (공급가+부가세)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (draft/sent/accepted/rejected)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='작성자'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_no')
    )
    op.create_index('idx_quotation_customer', 'quotations', ['customer_id'], unique=False)
    op.create_index('idx_quotation_date', 'quotations', ['quote_date'], unique=False)
    op.create_index('idx_quotation_status', 'quotations', ['status'], unique=False)
    op.create_table('quotation_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False, comment='라인 번호'),
    sa.Column('product_id', sa.UUID(), nullable=True, comment='품목'),
    sa.Column('product_name', sa.String(length=200), nullable=False, comment='품목명 (스냅샷)'),
    sa.Column('specification', sa.String(length=200), nullable=True, comment='규격'),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False, comment='수량'),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='단가'),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='할인율(%)'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='금액 (수량×단가×(1-할인))'),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='부가세'),
    sa.Column('delivery_date', sa.Date(), nullable=True, comment='납기일'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='비고'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.String(length=30), nullable=False, comment='수주번호 (SO-YYYYMM-NNNN)'),
    sa.Column('order_date', sa.Date(), nullable=False, comment='수주일'),
    sa.Column('delivery_date', sa.Date(), nullable=True, comment='납기일'),
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='거래처'),
    sa.Column('quotation_id', sa.UUID(), nullable=True, comment='연결 견적서'),
    sa.Column('sales_rep_id', sa.UUID(), nullable=True, comment='담당 영업사원'),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='공급가액 합계'),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='부가세 합계'),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False, comment='총액 (공급가+부가세)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (confirmed/in_production/shipped/completed/invoiced)'),
    sa.Column('progress_pct', sa.Integer(), nullable=False, comment='진행률 0~100%'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='작성자'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index('idx_order_customer', 'sales_orders', ['customer_id'], unique=False)
    op.create_index('idx_order_date', 'sales_orders', ['order_date'], unique=False)
    op.create_index('idx_order_status', 'sales_orders', ['status'], unique=False)
    op.create_table('sales_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False, comment='라인 번호'),
    sa.Column('product_id', sa.UUID(), nullable=True, comment='품목'),
    sa.Column('product_name', sa.String(length=200), nullable=False, comment='품목명 (스냅샷)'),
    sa.Column('specification', sa.String(length=200), nullable=True, comment='규격'),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False, comment='수주수량'),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='단가'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='금액'),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='부가세'),
    sa.Column('delivery_date', sa.Date(), nullable=True, comment='납기일'),
    sa.Column('produced_qty', sa.Numeric(precision=15, scale=3), nullable=False, comment='생산 완료 수량'),
    sa.Column('shipped_qty', sa.Numeric(precision=15, scale=3), nullable=False, comment='출하 완료 수량'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='비고'),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_order_lines')
    op.drop_index('idx_order_status', table_name='sales_orders')
    op.drop_index('idx_order_date', table_name='sales_orders')
    op.drop_index('idx_order_customer', table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_table('quotation_lines')
    op.drop_index('idx_quotation_status', table_name='quotations')
    op.drop_index('idx_quotation_date', table_name='quotations')
    op.drop_index('idx_quotation_customer', table_name='quotations')
    op.drop_table('quotations')
    # ### end Alembic commands ###
