"""m6_groupware_테이블_생성

Revision ID: 9c7d4a166604
Revises: c35a1fe2558c
Create Date: 2026-03-15 12:25:14.742012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c7d4a166604'
down_revision: Union[str, None] = 'c35a1fe2558c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_no', sa.String(length=30), nullable=False, comment='결재번호 (AP-YYYYMM-NNNN)'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='제목'),
    sa.Column('document_type', sa.String(length=30), nullable=False, comment='문서유형 (general/journal/quotation/sales_order/expense)'),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='품의 내용 (자유 형식)'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='금액'),
    sa.Column('reference_type', sa.String(length=30), nullable=True, comment='참조 유형 (journal/quotation/sales_order 등)'),
    sa.Column('reference_id', sa.UUID(), nullable=True, comment='참조 문서 ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (draft/pending/approved/rejected)'),
    sa.Column('requester_id', sa.UUID(), nullable=False, comment='기안자'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no')
    )
    op.create_index('idx_approval_reference', 'approval_requests', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_approval_requester', 'approval_requests', ['requester_id'], unique=False)
    op.create_index('idx_approval_status', 'approval_requests', ['status'], unique=False)
    op.create_table('approval_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='템플릿명'),
    sa.Column('document_type', sa.String(length=30), nullable=True, comment='문서유형 (general/journal/quotation/sales_order/expense)'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='제목'),
    sa.Column('content', sa.Text(), nullable=False, comment='내용'),
    sa.Column('is_pinned', sa.Boolean(), nullable=False, comment='상단 고정'),
    sa.Column('is_important', sa.Boolean(), nullable=False, comment='중요 표시'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='조회수'),
    sa.Column('author_id', sa.UUID(), nullable=False, comment='작성자'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notice_created', 'notices', ['created_at'], unique=False)
    op.create_index('idx_notice_pinned', 'notices', ['is_pinned'], unique=False)
    op.create_table('approval_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('step_type', sa.String(length=20), nullable=False, comment='유형 (approval/reference)'),
    sa.Column('step_order', sa.Integer(), nullable=False, comment='순서'),
    sa.Column('approver_id', sa.UUID(), nullable=False, comment='결재자/참조자'),
    sa.Column('role_label', sa.String(length=50), nullable=True, comment='역할명'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (pending/approved/rejected/viewed)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='의견'),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True, comment='처리일시'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_step_approver', 'approval_steps', ['approver_id'], unique=False)
    op.create_index('idx_step_approver_status', 'approval_steps', ['approver_id', 'status'], unique=False)
    op.create_index('idx_step_request', 'approval_steps', ['request_id'], unique=False)
    op.create_table('approval_template_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False, comment='순서'),
    sa.Column('approver_id', sa.UUID(), nullable=False, comment='결재자/참조자 ID'),
    sa.Column('role_label', sa.String(length=50), nullable=True, comment='역할명 (팀장, 대표이사 등)'),
    sa.Column('line_type', sa.String(length=20), nullable=False, comment='유형 (approval/reference)'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['approval_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_template_lines')
    op.drop_index('idx_step_request', table_name='approval_steps')
    op.drop_index('idx_step_approver_status', table_name='approval_steps')
    op.drop_index('idx_step_approver', table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index('idx_notice_pinned', table_name='notices')
    op.drop_index('idx_notice_created', table_name='notices')
    op.drop_table('notices')
    op.drop_table('approval_templates')
    op.drop_index('idx_approval_status', table_name='approval_requests')
    op.drop_index('idx_approval_requester', table_name='approval_requests')
    op.drop_index('idx_approval_reference', table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
