"""m3_인사급여_테이블_생성

Revision ID: a785c9044b3b
Revises: 55c454f5ad0d
Create Date: 2026-03-15 09:54:51.201178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a785c9044b3b'
down_revision: Union[str, None] = '55c454f5ad0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_no', sa.String(length=20), nullable=False, comment='사번'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='시스템 사용자 계정 링크'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='이름'),
    sa.Column('department_id', sa.UUID(), nullable=True, comment='부서'),
    sa.Column('position_id', sa.UUID(), nullable=True, comment='직급'),
    sa.Column('employee_type', sa.String(length=20), nullable=False, comment='고용 유형 (regular=정규직/contract=계약직/part=파트타임)'),
    sa.Column('hire_date', sa.Date(), nullable=False, comment='입사일'),
    sa.Column('resign_date', sa.Date(), nullable=True, comment='퇴사일'),
    sa.Column('base_salary', sa.Numeric(precision=15, scale=2), nullable=False, comment='기본급 (월)'),
    sa.Column('is_research_staff', sa.Boolean(), nullable=False, comment='R&D 인력 여부 (연구활동비 비과세 적용)'),
    sa.Column('annual_leave_days', sa.Integer(), nullable=False, comment='연차 일수'),
    sa.Column('remaining_leaves', sa.Numeric(precision=5, scale=1), nullable=False, comment='잔여 연차'),
    sa.Column('bank_name', sa.String(length=50), nullable=True, comment='급여 계좌 은행'),
    sa.Column('bank_account', sa.String(length=50), nullable=True, comment='급여 계좌번호'),
    sa.Column('resident_no_enc', sa.String(length=255), nullable=True, comment='주민등록번호 (암호화 저장)'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='연락처'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='개인 이메일'),
    sa.Column('address', sa.Text(), nullable=True, comment='주소'),
    sa.Column('has_childcare', sa.Boolean(), nullable=False, comment='육아수당 대상 여부'),
    sa.Column('has_car_allowance', sa.Boolean(), nullable=False, comment='자가운전보조금 대상 여부'),
    sa.Column('memo', sa.Text(), nullable=True, comment='비고'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='작성자'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_no'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_emp_active', 'employees', ['is_active'], unique=False)
    op.create_index('idx_emp_department', 'employees', ['department_id'], unique=False)
    op.create_index('idx_emp_hire_date', 'employees', ['hire_date'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='직원 ID'),
    sa.Column('work_date', sa.Date(), nullable=False, comment='근무일'),
    sa.Column('attendance_type', sa.String(length=20), nullable=False, comment='근태 유형 (normal=정상/leave=휴가/sick=병가/absent=결근/half=반차/early=조퇴)'),
    sa.Column('leave_type', sa.String(length=30), nullable=True, comment='휴가 종류 (annual=연차/sick=병가/special=특별휴가/half_am=오전반차/half_pm=오후반차)'),
    sa.Column('leave_days', sa.Numeric(precision=3, scale=1), nullable=False, comment='차감 일수 (0.5=반차, 1=연차)'),
    sa.Column('memo', sa.Text(), nullable=True, comment='사유'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='승인자'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='승인 일시'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_attendance_emp_date')
    )
    op.create_index('idx_att_date', 'attendance_records', ['work_date'], unique=False)
    op.create_index('idx_att_type', 'attendance_records', ['attendance_type'], unique=False)
    op.create_table('payroll_headers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_year', sa.Integer(), nullable=False, comment='귀속 연도'),
    sa.Column('payroll_month', sa.Integer(), nullable=False, comment='귀속 월'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (draft=작성중/calculated=계산완료/approved=승인/paid=지급완료)'),
    sa.Column('total_employees', sa.Integer(), nullable=False, comment='급여 대상 인원'),
    sa.Column('total_gross', sa.Numeric(precision=15, scale=2), nullable=False, comment='총 지급액 합계'),
    sa.Column('total_deduction', sa.Numeric(precision=15, scale=2), nullable=False, comment='총 공제액 합계'),
    sa.Column('total_net', sa.Numeric(precision=15, scale=2), nullable=False, comment='총 실수령액 합계'),
    sa.Column('payment_date', sa.Date(), nullable=True, comment='지급일'),
    sa.Column('journal_id', sa.UUID(), nullable=True, comment='연결된 전표 ID (급여 전표)'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='승인자'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='승인 일시'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='작성자'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_year', 'payroll_month', name='uq_payroll_year_month')
    )
    op.create_index('idx_payroll_status', 'payroll_headers', ['status'], unique=False)
    op.create_table('payroll_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_id', sa.UUID(), nullable=False, comment='급여대장 헤더 ID'),
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='직원 ID'),
    sa.Column('base_salary', sa.Numeric(precision=15, scale=2), nullable=False, comment='기본급'),
    sa.Column('overtime_pay', sa.Numeric(precision=15, scale=2), nullable=False, comment='초과근무수당'),
    sa.Column('bonus', sa.Numeric(precision=15, scale=2), nullable=False, comment='상여금'),
    sa.Column('meal_allowance', sa.Numeric(precision=15, scale=2), nullable=False, comment='식대 (비과세, 월 20만원 한도)'),
    sa.Column('car_allowance', sa.Numeric(precision=15, scale=2), nullable=False, comment='자가운전보조금 (비과세, 월 20만원 한도)'),
    sa.Column('research_allowance', sa.Numeric(precision=15, scale=2), nullable=False, comment='연구활동비 (비과세, 월 20만원 한도)'),
    sa.Column('childcare_allowance', sa.Numeric(precision=15, scale=2), nullable=False, comment='육아수당 (비과세, 월 10만원 한도)'),
    sa.Column('other_allowance', sa.Numeric(precision=15, scale=2), nullable=False, comment='기타 수당'),
    sa.Column('other_allowance_desc', sa.String(length=200), nullable=True, comment='기타 수당 설명'),
    sa.Column('gross_salary', sa.Numeric(precision=15, scale=2), nullable=False, comment='총 지급액 (과세+비과세 합계)'),
    sa.Column('taxable_salary', sa.Numeric(precision=15, scale=2), nullable=False, comment='과세 대상 급여 (총 지급액 - 비과세)'),
    sa.Column('income_tax', sa.Numeric(precision=15, scale=2), nullable=False, comment='소득세 (간이세액표)'),
    sa.Column('local_tax', sa.Numeric(precision=15, scale=2), nullable=False, comment='지방소득세 (소득세의 10%)'),
    sa.Column('national_pension', sa.Numeric(precision=15, scale=2), nullable=False, comment='국민연금 (4.5%)'),
    sa.Column('health_insurance', sa.Numeric(precision=15, scale=2), nullable=False, comment='건강보험 (3.545%)'),
    sa.Column('long_term_care', sa.Numeric(precision=15, scale=2), nullable=False, comment='장기요양보험 (건강보험의 12.81%)'),
    sa.Column('employment_insurance', sa.Numeric(precision=15, scale=2), nullable=False, comment='고용보험 (0.9%)'),
    sa.Column('total_deduction', sa.Numeric(precision=15, scale=2), nullable=False, comment='총 공제액'),
    sa.Column('net_salary', sa.Numeric(precision=15, scale=2), nullable=False, comment='실수령액'),
    sa.Column('work_days', sa.Integer(), nullable=False, comment='근무 일수'),
    sa.Column('leave_days', sa.Numeric(precision=3, scale=1), nullable=False, comment='휴가 일수'),
    sa.Column('absent_days', sa.Numeric(precision=3, scale=1), nullable=False, comment='결근 일수'),
    sa.Column('leave_deduction', sa.Numeric(precision=15, scale=2), nullable=False, comment='결근 공제액'),
    sa.Column('ai_optimized', sa.Boolean(), nullable=False, comment='AI 세무 최적화 적용 여부'),
    sa.Column('ai_memo', sa.Text(), nullable=True, comment='AI 최적화 메모'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_id'], ['payroll_headers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_id', 'employee_id', name='uq_payroll_employee')
    )
    op.create_index('idx_pd_employee', 'payroll_details', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pd_employee', table_name='payroll_details')
    op.drop_table('payroll_details')
    op.drop_index('idx_payroll_status', table_name='payroll_headers')
    op.drop_table('payroll_headers')
    op.drop_index('idx_att_type', table_name='attendance_records')
    op.drop_index('idx_att_date', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('idx_emp_hire_date', table_name='employees')
    op.drop_index('idx_emp_department', table_name='employees')
    op.drop_index('idx_emp_active', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
