"""M5 생산SCM 테이블 생성

Revision ID: c35a1fe2558c
Revises: 84eb4ff8723b
Create Date: 2026-03-15 11:37:17.663927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c35a1fe2558c'
down_revision: Union[str, None] = '84eb4ff8723b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False, comment='창고코드'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='창고명'),
    sa.Column('zone_type', sa.String(length=20), nullable=False, comment='구역유형 (raw/wip/finished/defective)'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('bom_headers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='완제품/반제품 ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='BOM 버전'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 여부'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version', name='uq_bom_product_version')
    )
    op.create_index('idx_bom_product', 'bom_headers', ['product_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False, comment='재고 수량'),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False, comment='단가'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (available/reserved)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_qty_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse_id', 'status', name='uq_inventory_product_warehouse_status')
    )
    op.create_index('idx_inventory_product', 'inventory', ['product_id'], unique=False)
    op.create_index('idx_inventory_warehouse', 'inventory', ['warehouse_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('from_warehouse_id', sa.UUID(), nullable=True, comment='출발 창고 (NULL이면 외부 입고)'),
    sa.Column('to_warehouse_id', sa.UUID(), nullable=True, comment='도착 창고 (NULL이면 외부 출고)'),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False, comment='이동 수량'),
    sa.Column('transaction_type', sa.String(length=20), nullable=False, comment='유형 (receive/issue/transfer/adjust)'),
    sa.Column('reference_type', sa.String(length=30), nullable=True, comment='참조 유형 (work_order/shipment/purchase/qc)'),
    sa.Column('reference_id', sa.UUID(), nullable=True, comment='참조 ID'),
    sa.Column('notes', sa.Text(), nullable=True, comment='메모'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_tx_created', 'inventory_transactions', ['created_at'], unique=False)
    op.create_index('idx_inv_tx_product', 'inventory_transactions', ['product_id'], unique=False)
    op.create_index('idx_inv_tx_product_date', 'inventory_transactions', ['product_id', 'created_at'], unique=False)
    op.create_index('idx_inv_tx_reference', 'inventory_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_table('bom_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bom_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False, comment='구성 자재(부품) ID'),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False, comment='소요 수량'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='단위'),
    sa.Column('scrap_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='스크랩율(%)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bom_headers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_no', sa.String(length=30), nullable=False, comment='출하번호 (SH-YYYYMM-NNNN)'),
    sa.Column('order_id', sa.UUID(), nullable=True, comment='수주 ID'),
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='거래처'),
    sa.Column('shipment_date', sa.Date(), nullable=True, comment='출하일'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (pending/picked/shipped/delivered)'),
    sa.Column('carrier_name', sa.String(length=100), nullable=True, comment='택배사명'),
    sa.Column('tracking_no', sa.String(length=100), nullable=True, comment='송장번호'),
    sa.Column('delivery_note_no', sa.String(length=30), nullable=True, comment='거래명세서 번호 (DN-YYYYMM-NNNN)'),
    sa.Column('shipping_address', sa.Text(), nullable=True, comment='배송 주소'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_no')
    )
    op.create_index('idx_shipment_customer', 'shipments', ['customer_id'], unique=False)
    op.create_index('idx_shipment_order', 'shipments', ['order_id'], unique=False)
    op.create_index('idx_shipment_status', 'shipments', ['status'], unique=False)
    op.create_table('shipment_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('order_line_id', sa.UUID(), nullable=True, comment='수주 라인 ID'),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False, comment='출하 수량'),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='단가 (수주 라인 스냅샷)'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='금액 (수량 x 단가)'),
    sa.Column('warehouse_id', sa.UUID(), nullable=True, comment='출고 창고'),
    sa.Column('line_no', sa.Integer(), nullable=False, comment='라인 번호'),
    sa.ForeignKeyConstraint(['order_line_id'], ['sales_order_lines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wo_no', sa.String(length=30), nullable=False, comment='작업지시번호 (WO-YYYYMM-NNNN)'),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment='유형 (make_to_order/make_to_stock)'),
    sa.Column('order_id', sa.UUID(), nullable=True, comment='수주 ID'),
    sa.Column('sales_order_line_id', sa.UUID(), nullable=True, comment='수주 라인 ID'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='생산 품목'),
    sa.Column('bom_id', sa.UUID(), nullable=True, comment='BOM ID'),
    sa.Column('planned_qty', sa.Numeric(precision=15, scale=3), nullable=False, comment='계획 수량'),
    sa.Column('produced_qty', sa.Numeric(precision=15, scale=3), nullable=False, comment='생산 완료 수량'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='시작일'),
    sa.Column('due_date', sa.Date(), nullable=False, comment='납기일'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (pending/in_progress/qc_wait/completed)'),
    sa.Column('assigned_to', sa.UUID(), nullable=True, comment='담당자'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bom_id'], ['bom_headers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_lines.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wo_no')
    )
    op.create_index('idx_wo_due_date', 'work_orders', ['due_date'], unique=False)
    op.create_index('idx_wo_order', 'work_orders', ['order_id'], unique=False)
    op.create_index('idx_wo_product', 'work_orders', ['product_id'], unique=False)
    op.create_index('idx_wo_status', 'work_orders', ['status'], unique=False)
    op.create_table('qc_inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=False, comment='작업지시서 ID'),
    sa.Column('inspected_qty', sa.Numeric(precision=15, scale=3), nullable=False, comment='검사 수량'),
    sa.Column('passed_qty', sa.Numeric(precision=15, scale=3), nullable=False, comment='합격 수량'),
    sa.Column('failed_qty', sa.Numeric(precision=15, scale=3), nullable=False, comment='불합격 수량'),
    sa.Column('result', sa.String(length=20), nullable=False, comment='결과 (pass/fail/rework)'),
    sa.Column('defect_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='불량 유형 (확장 가능)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='검사 메모'),
    sa.Column('inspector_id', sa.UUID(), nullable=True, comment='검사자'),
    sa.Column('inspected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qc_result', 'qc_inspections', ['result'], unique=False)
    op.create_index('idx_qc_work_order', 'qc_inspections', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_qc_work_order', table_name='qc_inspections')
    op.drop_index('idx_qc_result', table_name='qc_inspections')
    op.drop_table('qc_inspections')
    op.drop_index('idx_wo_status', table_name='work_orders')
    op.drop_index('idx_wo_product', table_name='work_orders')
    op.drop_index('idx_wo_order', table_name='work_orders')
    op.drop_index('idx_wo_due_date', table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_table('shipment_lines')
    op.drop_index('idx_shipment_status', table_name='shipments')
    op.drop_index('idx_shipment_order', table_name='shipments')
    op.drop_index('idx_shipment_customer', table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('bom_lines')
    op.drop_index('idx_inv_tx_reference', table_name='inventory_transactions')
    op.drop_index('idx_inv_tx_product_date', table_name='inventory_transactions')
    op.drop_index('idx_inv_tx_product', table_name='inventory_transactions')
    op.drop_index('idx_inv_tx_created', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index('idx_inventory_warehouse', table_name='inventory')
    op.drop_index('idx_inventory_product', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('idx_bom_product', table_name='bom_headers')
    op.drop_table('bom_headers')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
