"""m1_initial_schema

Revision ID: f35032d40e5a
Revises: 
Create Date: 2026-03-15 06:45:39.285121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f35032d40e5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='부서 코드'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='부서명'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='상위 부서'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=10), nullable=False, comment='모듈 (M1~M7)'),
    sa.Column('feature_id', sa.String(length=20), nullable=False, comment='기능 ID'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='동작 (read/write/delete/approve)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'feature_id', 'action', name='uq_permission_module_feature_action')
    )
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='직급 코드'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='직급명'),
    sa.Column('level', sa.Integer(), nullable=False, comment='직급 레벨'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False, comment='분류 코드'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='분류명'),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permission_id', name='uq_role_permission')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_no', sa.String(length=20), nullable=False, comment='사번'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='이름'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='비밀번호 해시'),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False, comment='역할 (admin/manager/user)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_no')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False, comment='변경된 테이블'),
    sa.Column('record_id', sa.UUID(), nullable=False, comment='변경된 레코드 ID'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='INSERT/UPDATE/DELETE'),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='변경 전 데이터'),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='변경 후 데이터'),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='요청자 IP'),
    sa.Column('memo', sa.Text(), nullable=True, comment='수정 사유'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_changed_at', 'audit_logs', ['changed_at'], unique=False)
    op.create_index('idx_audit_logs_table', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False, comment='거래처 코드'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='거래처명'),
    sa.Column('business_no', sa.String(length=20), nullable=True, comment='사업자등록번호'),
    sa.Column('ceo_name', sa.String(length=50), nullable=True, comment='대표자명'),
    sa.Column('business_type', sa.String(length=100), nullable=True, comment='업태'),
    sa.Column('business_item', sa.String(length=100), nullable=True, comment='종목'),
    sa.Column('address', sa.Text(), nullable=True, comment='주소'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='전화번호'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='이메일'),
    sa.Column('fax', sa.String(length=30), nullable=True, comment='팩스'),
    sa.Column('contact_person', sa.String(length=50), nullable=True, comment='담당자명'),
    sa.Column('customer_type', sa.String(length=20), nullable=False, comment='유형 (customer/supplier/both)'),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False, comment='신용한도'),
    sa.Column('payment_terms', sa.Integer(), nullable=False, comment='결제조건 (일)'),
    sa.Column('bank_name', sa.String(length=50), nullable=True, comment='은행명'),
    sa.Column('bank_account', sa.String(length=50), nullable=True, comment='계좌번호'),
    sa.Column('bank_account_name', sa.String(length=50), nullable=True, comment='예금주'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mdm_status', sa.String(length=20), nullable=False, comment='MDM 상태 (pending/approved/rejected)'),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_no'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_customers_business_no', 'customers', ['business_no'], unique=False)
    op.create_index('idx_customers_name', 'customers', ['name'], unique=False)
    op.create_table('form_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=10), nullable=False, comment='모듈 (M1~M7)'),
    sa.Column('form_name', sa.String(length=100), nullable=False, comment='폼 이름'),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='필드 구성 JSON'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'form_name', 'version', name='uq_form_config_module_name_ver')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='품목 코드'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='품목명'),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=False, comment='유형 (product/material/semi)'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='단위'),
    sa.Column('standard_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='기준 단가'),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='원가'),
    sa.Column('safety_stock', sa.Integer(), nullable=False, comment='안전재고'),
    sa.Column('inventory_method', sa.String(length=20), nullable=False, comment='재고평가 (fifo/avg)'),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='부가세율'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mdm_status', sa.String(length=20), nullable=False, comment='MDM 상태'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('form_configs')
    op.drop_index('idx_customers_name', table_name='customers')
    op.drop_index('idx_customers_business_no', table_name='customers')
    op.drop_table('customers')
    op.drop_index('idx_audit_logs_table', table_name='audit_logs')
    op.drop_index('idx_audit_logs_changed_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('product_categories')
    op.drop_table('positions')
    op.drop_table('permissions')
    op.drop_table('departments')
    # ### end Alembic commands ###
